spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    pet:
      url: jdbc:postgresql://localhost:5432/pet
      username: admin
      password: admin
    contact:
      url: jdbc:postgresql://localhost:5433/contact
      username: admin
      password: admin
  data:
    mongodb:
      database: CHARACTER_DB
      uri: mongodb://${mongo.user}:${mongo.password}@${mongo.host}

mongo:
  user: root
  password: example
  sslstate: false
  host: 127.0.0.1:27017
  dbname: CHARACTER_DB

